name: woo_study_case
description: A new Flutter projector Woo Network.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: 3.0.0

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.4
  google_fonts: ^2.3.2
  auto_size_text: ^3.0.0

  # State Management & DI
  riverpod: ^2.0.0-dev.6 

  # Data Class
  freezed_annotation: ^2.0.3
  
  # Utils
  json_annotation: ^4.5.0
  dart_code_metrics: ^4.15.0
  collection: ^1.15.0



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.4

  # Data Class
  freezed: ^2.0.3

  # Generator
  build_runner: ^2.1.10
  analyzer: ^4.0.0
  json_serializable: ^6.2.0

dependency_overrides:
  analyzer:

flutter:
  uses-material-design: true
  assets:
    - assets/